Ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('api-auth/', include('rest_framework.urls')),
]

main/urls.py
from django.urls import path
from . import views

from django.conf.urls import url

from .views import *

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    ###############  FRONTEND URLS ###############

    path('', views.home, name='home'),
    path('search', views.search, name='search'),
    path('category-list', views.category_list, name='category-list'),
    path('brand-list', views.brand_list, name='brand-list'),
    path('product-list', views.product_list, name='product-list'),
    path('category-product-list/<int:cat_id>', views.category_product_list, name='category-product-list'),
    path('brand-product-list/<int:brand_id>', views.brand_product_list, name='brand-product-list'),
    path('product/<str:slug>/<int:id>', views.product_detail, name='product-detail'),
    path("filter-data", views.filter_data, name="filter_data"),
    path("addToFavourite-<int:id>", views.add_to_favourite, name="addToFavourite"),
    
    
    ###############  CART URLS ################
    
    path("add-to-cart-<int:pro_id>/", AddToCartView.as_view(), name="addtocart"),
    path("my-cart/", MyCartView.as_view(), name="mycart"),
    path("manage-cart/<int:cp_id>", ManageCartView.as_view(), name="managecart"),
    path("empty-cart/", EmptyCartView.as_view(), name="emptycart"),
    path("checkout/", CheckoutView.as_view(), name="checkout"),
    path("razorpay-request/", RazorpayRequestView.as_view(), name="razorpayrequest"),
    path('success' , views.success , name='success'),
    

    ################ CUSTOMER URLS ################
    
    path("register/",
         CustomerRegistrationView.as_view(), name="customerregistration"),
    path("logout/", CustomerLogoutView.as_view(), name="customerlogout"),
    path("login/", CustomerLoginView.as_view(), name="customerlogin"),
    path("profile-<int:id>", CustomerProfileView.as_view(), name="customerprofile"),
    path('forgot-password', PasswordForgotView.as_view(), name="passwordforgot"),
    path("password-reset/<email>/<token>/", PasswordResetView.as_view(), name="passwordreset"),


    ################ REST URLS #################

    url(r'^products/$', views.product_rest_list),


    ################ ADMIN URLS #################
    
    ##### ADMIN HOME #####
    path("admin-home/", AdminHomeView.as_view(), name="adminhome"),
    
    ##### ADMIN READ URLS #####    
    path('admin-product-list', AdminProductListView.as_view(), name="adminProductList"),
    path('admin-brand-list', AdminBrandListView.as_view(), name="adminBrandList"),
    path('admin-category-list', AdminCategoryListView.as_view(), name="adminCategoryList"),
    path('admin-user-list', AdminUserListView.as_view(), name="adminUserList"),
    path("admin-order-list", AdminOrderListView.as_view(), name="adminOrderList"),
    path("admin-order-details/<int:ord_id>", AdminOrderDetails.as_view(), name="adminOrderDetails"),
    path("admin-color-list", AdminColorListView.as_view(), name="adminColorList"),
    path("admin-size-list", AdminSizeListView.as_view(), name="adminSizeList"),
    path("admin-pattr-list-<int:prod_id>", AdminProdcutAttributesView.as_view(), name="adminPattr"),

    ##### ADMIN CREATE URLS #####
    path('admin-add-product', AddProductView.as_view(), name='addProduct'),
    path('admin-add-product-attribute', AddProductAttributeView.as_view(), name='addProductAttribute'),
    path('admin-add-brand', AddBrandView.as_view(), name='addBrand'),
    path('admin-add-category', AddCategoryView.as_view(), name='addCategory'),
    path('admin-add-user', AddCustomerView.as_view(), name='addCustomer'),
    path('admin-add-color', AddColorView.as_view(), name='addColor'),
    path('admin-add-size', AddSizeView.as_view(), name="addSize"),

    ##### ADMIN EDIT URLS #####
    path("admin-edit-product-<int:pk>", ProductUpdateView.as_view(), name="productUpdate"),
    path("admin-edit-brand-<int:pk>", BrandUpdateView.as_view(), name="brandUpdate"),
    path("admin-edit-category-<int:pk>", CategoryUpdateView.as_view(), name="categoryUpdate"),
    path("admin-edit-user-<int:pk>", UserUpdateView.as_view(), name="userUpdate"),
    path('admin-order-status-change-<int:ord_id>', AdminOrderStatusChange.as_view(), name='adminOrderStatusChange'),
    path('admin-edit-color-<int:pk>', ColorUpdateView.as_view(), name="colorUpdate"),
    path('admin-edit-size-<int:pk>', SizeUpdateView.as_view(), name="sizeUpdate"),
    path('admin-edit-pattr=<int:pk>', ProductAttrUpdateView.as_view(), name="pattrUpdate"),

    ##### ADMIN DELETE URLS #####
    path("delete-product/<int:prod_id>", DeleteProduct.as_view(), name="deleteproduct"),
    path("delete-brand/<int:brand_id>", DeleteBrand.as_view(), name="deletebrand"),
    path("delete-category/<int:cat_id>", DeleteCategory.as_view(), name="deletecategory"),
    path("delete-customer/<int:cust_id>", DeleteCustomer.as_view(), name="deletecustomer"),
    path("delete-order/<int:ord_id>", DeleteOrder.as_view(), name="deleteorder"),
    path("delete-color/<int:col_id>", DeleteColor.as_view(), name="deletecolor"),
    path("delete-size/<int:size_id>", DeleteSize.as_view(), name="deletesize"),
    path("delete-pattr/<int:pattr_id>", DeleteProductAttribute.as_view(), name="deletepattr"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.utils.html import mark_safe
from django.contrib.auth.models import User

# Customer Model
class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=200)
    address = models.CharField(max_length=200, null=True, blank=True)
    joined_on = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name_plural = 'Customers'

    def __str__(self):
        return self.full_name

# Banner Model
class Banner(models.Model):
    img = models.ImageField(upload_to='banner_imgs/')
    alt_text = models.CharField(max_length=300)

    class Meta:
        verbose_name_plural = '1. Banners'

    def image_tag(self):
        return mark_safe('<img src="%s" width="130" height="50" />' % (self.img.url))

    def __str__(self):
        return self.alt_text

# Category Model
class Category(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to="cat_imgs/")

    class Meta:
        verbose_name_plural = '2. Categories'

    def image_tag(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))

    def __str__(self):
        return self.title

# Brand Model
class Brand(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to="brand_imgs/")

    class Meta:
        verbose_name_plural = '3. Brands'

    def image_tag(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))

    def __str__(self):
        return self.title

# Color Model
class Color(models.Model):
    title = models.CharField(max_length=100)
    color_code = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = '4. Colors'

    def color_bg(self):
        return mark_safe('<div style="width:40px; height:20px; background:%s"></div>' % (self.color_code))
    
    def __str__(self):
        return self.title

# Size Model
class Size(models.Model):
    title = models.CharField(max_length=100)
    
    class Meta:
        verbose_name_plural = '5. Sizes'

    def __str__(self):
        return self.title

# Product Model
class Product(models.Model):
    title = models.CharField(max_length=200)
    slug = models.CharField(max_length=400)
    details = models.TextField()
    specs = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    status = models.BooleanField(default=True)
    price = models.PositiveIntegerField(null=True)
    is_featured = models.BooleanField(default=False)
    favorite = models.ManyToManyField(Customer, blank=True)

    class Meta:
        verbose_name_plural = '6. Products'

    def __str__(self):
        return self.title

# Product Attributes Model
class ProductAttribute(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    color = models.ForeignKey(Color, on_delete=models.CASCADE)
    size = models.ForeignKey(Size, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="product_imgs/", null=True)

    class Meta:
        verbose_name_plural = '7. ProductAttributes'

    def image_tag(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))

    def __str__(self):
        return self.product.title

# Cart Model
class Cart(models.Model):
    customer = models.ForeignKey(
        Customer, on_delete=models.SET_NULL, null=True, blank=True)
    total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = '8. Cart'

    def __str__(self):
        return "Cart: " + str(self.id)

# Cart Product Model
class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rate = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()

    class Meta:
        verbose_name_plural = '9. Cart Products'

    def __str__(self):
        return "Cart: " + str(self.cart.id) + " CartProduct: " + str(self.id)


ORDER_STATUS = (
    ("Order Received", "Order Received"),
    ("Order Processing", "Order Processing"),
    ("On the way", "On the way"),
    ("Order Completed", "Order Completed"),
    ("Order Canceled", "Order Canceled"),
)

METHOD = (
    ("Cash On Delivery", "Cash On Delivery"),
    ("Razorpay", "Razorpay")
)

# Order Model
class Order(models.Model):
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    ordered_by = models.CharField(max_length=200)
    shipping_address = models.CharField(max_length=200)
    mobile = models.CharField(max_length=10)
    email = models.EmailField(null=True, blank=True)
    subtotal = models.PositiveIntegerField()
    discount = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    order_status = models.CharField(max_length=50, choices=ORDER_STATUS)
    created_at = models.DateTimeField(auto_now_add=True)
    payment_method = models.CharField(max_length=20, choices=METHOD, default="Cash On Delivery")
    payment_completed = models.BooleanField(default=False)

    def __str__(self):
        return "Order: " + str(self.id)

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import *

# Checkout Form
class CheckoutForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ["ordered_by", "shipping_address",
                  "mobile", "email", "payment_method"]

# Customer Registration Form
class CustomerRegistrationForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())
    email = forms.CharField(widget=forms.EmailInput())

    class Meta:
        model = Customer
        fields = ["username", "password", "email", "full_name", "address"]

    def clean_username(self):
        uname = self.cleaned_data.get("username")
        if User.objects.filter(username=uname).exists():
            raise forms.ValidationError(
                "Customer with this username already exists.")

        return uname

# Customer Login Form
class CustomerLoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())

    def clean_username(self):
        uname = self.cleaned_data.get("username")
        if User.objects.filter(username=uname).exists():
            pass
        else:
            raise forms.ValidationError(
                "*Customer with this username does not exist.")

        return uname

# Forgot Password Form
class PasswordForgotForm(forms.Form):
    email = forms.CharField(
        widget=forms.EmailInput(
            attrs={
                "class": "form-control",
                "placeholder": "Enter the mail used in your account...."
            }))

    def clean_email(self):
        e = self.cleaned_data.get("email")
        if Customer.objects.filter(user__email=e).exists():
            pass
        else:
            raise forms.ValidationError(
                "Customer with this email does not exist. Please try again!"
            )
        return e  

# Password Reset Form
class PasswordResetForm(forms.Form):
    new_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'autocomplete': 'new-password',
        'placeholder': 'Enter New Password',
    }), label="New Password")
    confirm_new_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'autocomplete': 'new-password',
        'placeholder': 'Confirm New Password',
    }), label="Confirm New Password")

    def clean_confirm_new_password(self):
        new_password = self.cleaned_data.get("new_password")
        confirm_new_password = self.cleaned_data.get("confirm_new_password")
        if new_password != confirm_new_password:
            raise forms.ValidationError(
                "Passwords did not match!")
        return confirm_new_password

# Product Add Form
class ProductAddForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput())
    slug = forms.CharField(widget=forms.TextInput())
    details = forms.CharField(widget=forms.Textarea)
    specs = forms.CharField(widget=forms.Textarea)
    category = forms.ModelChoiceField(queryset=Category.objects.all(), required=True)
    brand = forms.ModelChoiceField(queryset=Brand.objects.all(), required=True)
    price = forms.IntegerField(widget=forms.NumberInput())
    is_featured = forms.BooleanField(required=False,initial=False,label='Featured')

    class Meta:
        model = Product
        fields = ["title", "slug", "details",
                  "specs", "category", "brand",
                  "price", "is_featured"]
    
# Product Attribute Form
class ProductAttributeForm(forms.ModelForm):
    product = forms.ModelChoiceField(queryset=Product.objects.all())
    color = forms.ModelChoiceField(queryset=Color.objects.all())
    size = forms.ModelChoiceField(queryset=Size.objects.all())
    image = forms.FileField()
    
    class Meta:
        model = ProductAttribute
        fields = ["product", "color", "size", "image"]

# Brand Add Form
class BrandAddForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput())
    image = forms.FileField()

    class Meta:
        model = Brand
        fields = ["title", "image"]

# Category Add Form
class CategoryAddForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput())
    image = forms.FileField()

    class Meta:
        model = Category
        fields = ["title", "image"]

# Color Add Form
class ColorAddForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput())
    color_code = forms.CharField(widget=forms.TextInput())

    class Meta:
        model = Color
        fields = ["title", "color_code"]

# Size Add Form
class SizeAddForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput())

    class Meta:
        model = Size
        fields = ["title"]

main/templates/cart/addtocart.html
{% extends 'base.html' %}

{% block title %}Add to cart{% endblock %}

{% block content %}
<div class="container">
    <h3>Product added to cart successfully.</h3>
</div>
{% endblock %}

main/templates/cart/checkout.html
{% extends 'base.html' %}

{% block title %}Checkout {% endblock %}
{% load crispy_forms_tags %}
{% load mathfilters %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h3 class="mt-5 mb-4">Items in the cart</h3>
            <table class="table table-hover">
                <thead class="thead-dark">
                    <tr>
                        <th>SN</th>
                        <th>Product</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cp in cart.cartproduct_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{cp.product.title}}</td>
                        <td>{{cp.rate}}</td>
                        <td>{{cp.quantity}}</td>
                        <td>{{cp.subtotal}}</td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th colspan="3"><a href="{% url 'mycart' %}" class="btn btn-success">Update Cart</a></th>
                        <th class="text-right">Total</th>
                        <th>Rs. {{cart.total}}</th>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="col-md-6 mt-5 mb-4">
            <h3>Checkout Form</h3>
            <form action="" method="POST">
                {% csrf_token %}
                {{form|crispy}}
                <br/>
                <button class="btn btn-info">Place order</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

main/templates/cart/mycart.html
{% extends 'base.html' %}

{% block title %} My cart{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-10">
            <h4>Items in my cart</h4><hr>
            <div class="table-responsive">
            <table class="table table-bordered table-hover">
                <thead class="thead-dark">
                    <tr>
                        <th>SN</th>
                        <th>Product</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                        <th colspan="2">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cp in cart.cartproduct_set.all %}
                    <tr>
                        <th scope="row">{{forloop.counter}}</th>
                        <td>{{cp.product.title}}</td>
                        <td>{{cp.rate}}</td>
                        <td>{{cp.quantity}}</td>
                        <td>{{cp.subtotal}}</td>
                        <td colspan="2">
                            <a href="{% url 'managecart' cp.id %}?action=inc" class="btn btn-primary"> ADD </a>
                            <a href="{% url 'managecart' cp.id %}?action=dcr" class="btn btn-warning"> REMOVE </a>
                            <a href="{% url 'managecart' cp.id %}?action=rmv" class="btn btn-danger"> DEL </a>
                        </td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th colspan="4" class="text-right">Total</th>
                        <th>Rs. {{cart.total}}</th>
                        {% if cart.cartproduct_set.all %}
                        <th><a href="{% url 'emptycart' %}">Empty Cart</a></th>
                        {% endif %}
                    </tr>
                    {% if cart.cartproduct_set.all %}
                    <tr>
                        <th><a class="btn btn-info" href="{% url 'checkout' %}"> Checkout </a></th>
                    </tr>
                    {% endif %}
                </tbody>
            </table></div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/cart/razorpay_payment.html
<form action="" method="POST">
<script
        src="https://checkout.razorpay.com/v1/checkout.js"
        data-key="rzp_test_ejxwUwJ32rcHr9" 
        data-amount="{{ order.total|mul:100 }}" 
        data-currency="INR"
        data-order_id="{{payment.id}}"
        data-buttontext="Pay with Razorpay"
        data-name="ShopIT"
        data-description="Ecommerce Website"
        data-image="https://example.com/your_logo.jpg"
        data-prefill.name="John Doe"
        data-prefill.email="john.doe@example.com"
        data-theme.color="#F37254">
</script>
</form>