Ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('api-auth/', include('rest_framework.urls')),
]

main/urls.py
from django.urls import path
from . import views

from django.conf.urls import url

from .views import *

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    ###############  FRONTEND URLS ###############

    path('', views.home, name='home'),
    path('search', views.search, name='search'),
    path('category-list', views.category_list, name='category-list'),
    path('brand-list', views.brand_list, name='brand-list'),
    path('product-list', views.product_list, name='product-list'),
    path('category-product-list/<int:cat_id>', views.category_product_list, name='category-product-list'),
    path('brand-product-list/<int:brand_id>', views.brand_product_list, name='brand-product-list'),
    path('product/<str:slug>/<int:id>', views.product_detail, name='product-detail'),
    path("filter-data", views.filter_data, name="filter_data"),
    path("addToFavourite-<int:id>", views.add_to_favourite, name="addToFavourite"),
    
    
    ###############  CART URLS ################
    
    path("add-to-cart-<int:pro_id>/", AddToCartView.as_view(), name="addtocart"),
    path("my-cart/", MyCartView.as_view(), name="mycart"),
    path("manage-cart/<int:cp_id>", ManageCartView.as_view(), name="managecart"),
    path("empty-cart/", EmptyCartView.as_view(), name="emptycart"),
    path("checkout/", CheckoutView.as_view(), name="checkout"),
    path("razorpay-request/", RazorpayRequestView.as_view(), name="razorpayrequest"),
    path('success' , views.success , name='success'),
    

    ################ CUSTOMER URLS ################
    
    path("register/",
         CustomerRegistrationView.as_view(), name="customerregistration"),
    path("logout/", CustomerLogoutView.as_view(), name="customerlogout"),
    path("login/", CustomerLoginView.as_view(), name="customerlogin"),
    path("profile-<int:id>", CustomerProfileView.as_view(), name="customerprofile"),
    path('forgot-password', PasswordForgotView.as_view(), name="passwordforgot"),
    path("password-reset/<email>/<token>/", PasswordResetView.as_view(), name="passwordreset"),


    ################ REST URLS #################

    url(r'^products/$', views.product_rest_list),


    ################ ADMIN URLS #################
    
    ##### ADMIN HOME #####
    path("admin-home/", AdminHomeView.as_view(), name="adminhome"),
    
    ##### ADMIN READ URLS #####    
    path('admin-product-list', AdminProductListView.as_view(), name="adminProductList"),
    path('admin-brand-list', AdminBrandListView.as_view(), name="adminBrandList"),
    path('admin-category-list', AdminCategoryListView.as_view(), name="adminCategoryList"),
    path('admin-user-list', AdminUserListView.as_view(), name="adminUserList"),
    path("admin-order-list", AdminOrderListView.as_view(), name="adminOrderList"),
    path("admin-order-details/<int:ord_id>", AdminOrderDetails.as_view(), name="adminOrderDetails"),
    path("admin-color-list", AdminColorListView.as_view(), name="adminColorList"),
    path("admin-size-list", AdminSizeListView.as_view(), name="adminSizeList"),
    path("admin-pattr-list-<int:prod_id>", AdminProdcutAttributesView.as_view(), name="adminPattr"),

    ##### ADMIN CREATE URLS #####
    path('admin-add-product', AddProductView.as_view(), name='addProduct'),
    path('admin-add-product-attribute', AddProductAttributeView.as_view(), name='addProductAttribute'),
    path('admin-add-brand', AddBrandView.as_view(), name='addBrand'),
    path('admin-add-category', AddCategoryView.as_view(), name='addCategory'),
    path('admin-add-user', AddCustomerView.as_view(), name='addCustomer'),
    path('admin-add-color', AddColorView.as_view(), name='addColor'),
    path('admin-add-size', AddSizeView.as_view(), name="addSize"),

    ##### ADMIN EDIT URLS #####
    path("admin-edit-product-<int:pk>", ProductUpdateView.as_view(), name="productUpdate"),
    path("admin-edit-brand-<int:pk>", BrandUpdateView.as_view(), name="brandUpdate"),
    path("admin-edit-category-<int:pk>", CategoryUpdateView.as_view(), name="categoryUpdate"),
    path("admin-edit-user-<int:pk>", UserUpdateView.as_view(), name="userUpdate"),
    path('admin-order-status-change-<int:ord_id>', AdminOrderStatusChange.as_view(), name='adminOrderStatusChange'),
    path('admin-edit-color-<int:pk>', ColorUpdateView.as_view(), name="colorUpdate"),
    path('admin-edit-size-<int:pk>', SizeUpdateView.as_view(), name="sizeUpdate"),
    path('admin-edit-pattr=<int:pk>', ProductAttrUpdateView.as_view(), name="pattrUpdate"),

    ##### ADMIN DELETE URLS #####
    path("delete-product/<int:prod_id>", DeleteProduct.as_view(), name="deleteproduct"),
    path("delete-brand/<int:brand_id>", DeleteBrand.as_view(), name="deletebrand"),
    path("delete-category/<int:cat_id>", DeleteCategory.as_view(), name="deletecategory"),
    path("delete-customer/<int:cust_id>", DeleteCustomer.as_view(), name="deletecustomer"),
    path("delete-order/<int:ord_id>", DeleteOrder.as_view(), name="deleteorder"),
    path("delete-color/<int:col_id>", DeleteColor.as_view(), name="deletecolor"),
    path("delete-size/<int:size_id>", DeleteSize.as_view(), name="deletesize"),
    path("delete-pattr/<int:pattr_id>", DeleteProductAttribute.as_view(), name="deletepattr"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.utils.html import mark_safe
from django.contrib.auth.models import User

# Customer Model
class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=200)
    address = models.CharField(max_length=200, null=True, blank=True)
    joined_on = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name_plural = 'Customers'

    def __str__(self):
        return self.full_name

# Banner Model
class Banner(models.Model):
    img = models.ImageField(upload_to='banner_imgs/')
    alt_text = models.CharField(max_length=300)

    class Meta:
        verbose_name_plural = '1. Banners'

    def image_tag(self):
        return mark_safe('<img src="%s" width="130" height="50" />' % (self.img.url))

    def __str__(self):
        return self.alt_text

# Category Model
class Category(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to="cat_imgs/")

    class Meta:
        verbose_name_plural = '2. Categories'

    def image_tag(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))

    def __str__(self):
        return self.title

# Brand Model
class Brand(models.Model):
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to="brand_imgs/")

    class Meta:
        verbose_name_plural = '3. Brands'

    def image_tag(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))

    def __str__(self):
        return self.title

# Color Model
class Color(models.Model):
    title = models.CharField(max_length=100)
    color_code = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = '4. Colors'

    def color_bg(self):
        return mark_safe('<div style="width:40px; height:20px; background:%s"></div>' % (self.color_code))
    
    def __str__(self):
        return self.title

# Size Model
class Size(models.Model):
    title = models.CharField(max_length=100)
    
    class Meta:
        verbose_name_plural = '5. Sizes'

    def __str__(self):
        return self.title

# Product Model
class Product(models.Model):
    title = models.CharField(max_length=200)
    slug = models.CharField(max_length=400)
    details = models.TextField()
    specs = models.TextField()
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    status = models.BooleanField(default=True)
    price = models.PositiveIntegerField(null=True)
    is_featured = models.BooleanField(default=False)
    favorite = models.ManyToManyField(Customer, blank=True)

    class Meta:
        verbose_name_plural = '6. Products'

    def __str__(self):
        return self.title

# Product Attributes Model
class ProductAttribute(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    color = models.ForeignKey(Color, on_delete=models.CASCADE)
    size = models.ForeignKey(Size, on_delete=models.CASCADE)
    image = models.ImageField(upload_to="product_imgs/", null=True)

    class Meta:
        verbose_name_plural = '7. ProductAttributes'

    def image_tag(self):
        return mark_safe('<img src="%s" width="50" height="50" />' % (self.image.url))

    def __str__(self):
        return self.product.title

# Cart Model
class Cart(models.Model):
    customer = models.ForeignKey(
        Customer, on_delete=models.SET_NULL, null=True, blank=True)
    total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = '8. Cart'

    def __str__(self):
        return "Cart: " + str(self.id)

# Cart Product Model
class CartProduct(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rate = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()

    class Meta:
        verbose_name_plural = '9. Cart Products'

    def __str__(self):
        return "Cart: " + str(self.cart.id) + " CartProduct: " + str(self.id)


ORDER_STATUS = (
    ("Order Received", "Order Received"),
    ("Order Processing", "Order Processing"),
    ("On the way", "On the way"),
    ("Order Completed", "Order Completed"),
    ("Order Canceled", "Order Canceled"),
)

METHOD = (
    ("Cash On Delivery", "Cash On Delivery"),
    ("Razorpay", "Razorpay")
)

# Order Model
class Order(models.Model):
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    ordered_by = models.CharField(max_length=200)
    shipping_address = models.CharField(max_length=200)
    mobile = models.CharField(max_length=10)
    email = models.EmailField(null=True, blank=True)
    subtotal = models.PositiveIntegerField()
    discount = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    order_status = models.CharField(max_length=50, choices=ORDER_STATUS)
    created_at = models.DateTimeField(auto_now_add=True)
    payment_method = models.CharField(max_length=20, choices=METHOD, default="Cash On Delivery")
    payment_completed = models.BooleanField(default=False)

    def __str__(self):
        return "Order: " + str(self.id)

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import *

# Checkout Form
class CheckoutForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ["ordered_by", "shipping_address",
                  "mobile", "email", "payment_method"]

# Customer Registration Form
class CustomerRegistrationForm(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())
    email = forms.CharField(widget=forms.EmailInput())

    class Meta:
        model = Customer
        fields = ["username", "password", "email", "full_name", "address"]

    def clean_username(self):
        uname = self.cleaned_data.get("username")
        if User.objects.filter(username=uname).exists():
            raise forms.ValidationError(
                "Customer with this username already exists.")

        return uname

# Customer Login Form
class CustomerLoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput())
    password = forms.CharField(widget=forms.PasswordInput())

    def clean_username(self):
        uname = self.cleaned_data.get("username")
        if User.objects.filter(username=uname).exists():
            pass
        else:
            raise forms.ValidationError(
                "*Customer with this username does not exist.")

        return uname

# Forgot Password Form
class PasswordForgotForm(forms.Form):
    email = forms.CharField(
        widget=forms.EmailInput(
            attrs={
                "class": "form-control",
                "placeholder": "Enter the mail used in your account...."
            }))

    def clean_email(self):
        e = self.cleaned_data.get("email")
        if Customer.objects.filter(user__email=e).exists():
            pass
        else:
            raise forms.ValidationError(
                "Customer with this email does not exist. Please try again!"
            )
        return e  

# Password Reset Form
class PasswordResetForm(forms.Form):
    new_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'autocomplete': 'new-password',
        'placeholder': 'Enter New Password',
    }), label="New Password")
    confirm_new_password = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control',
        'autocomplete': 'new-password',
        'placeholder': 'Confirm New Password',
    }), label="Confirm New Password")

    def clean_confirm_new_password(self):
        new_password = self.cleaned_data.get("new_password")
        confirm_new_password = self.cleaned_data.get("confirm_new_password")
        if new_password != confirm_new_password:
            raise forms.ValidationError(
                "Passwords did not match!")
        return confirm_new_password

# Product Add Form
class ProductAddForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput())
    slug = forms.CharField(widget=forms.TextInput())
    details = forms.CharField(widget=forms.Textarea)
    specs = forms.CharField(widget=forms.Textarea)
    category = forms.ModelChoiceField(queryset=Category.objects.all(), required=True)
    brand = forms.ModelChoiceField(queryset=Brand.objects.all(), required=True)
    price = forms.IntegerField(widget=forms.NumberInput())
    is_featured = forms.BooleanField(required=False,initial=False,label='Featured')

    class Meta:
        model = Product
        fields = ["title", "slug", "details",
                  "specs", "category", "brand",
                  "price", "is_featured"]
    
# Product Attribute Form
class ProductAttributeForm(forms.ModelForm):
    product = forms.ModelChoiceField(queryset=Product.objects.all())
    color = forms.ModelChoiceField(queryset=Color.objects.all())
    size = forms.ModelChoiceField(queryset=Size.objects.all())
    image = forms.FileField()
    
    class Meta:
        model = ProductAttribute
        fields = ["product", "color", "size", "image"]

# Brand Add Form
class BrandAddForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput())
    image = forms.FileField()

    class Meta:
        model = Brand
        fields = ["title", "image"]

# Category Add Form
class CategoryAddForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput())
    image = forms.FileField()

    class Meta:
        model = Category
        fields = ["title", "image"]

# Color Add Form
class ColorAddForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput())
    color_code = forms.CharField(widget=forms.TextInput())

    class Meta:
        model = Color
        fields = ["title", "color_code"]

# Size Add Form
class SizeAddForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput())

    class Meta:
        model = Size
        fields = ["title"]

main/templates/addProducts.html
{% extends 'adminbase.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <br />
            <h3>Add Product</h3><hr>
            <form action="" method="POST">
                {% csrf_token %}
                {{form|crispy}}
                <button class="btn btn-primary mt-3">Add Product</button>
            </form>
        </div>
    </div>
</div>

{% endblock %}

main/templates/adminHome2.html
{% extends 'adminbase3.html' %}
{% load static %}
{% load humanize %}
{% block title %} ShopIT Admin-Panel {% endblock %}
{% block content %}
<div class="row">
<div class="col main pt-5 mt-3">
    <h1 class="display-4 d-none d-sm-block">
            Admin Dashboard
            </h1>
            <div class="row mb-3">
                <div class="col-xl-6 col-sm-6 py-2">
                    <div class="card bg-success text-white text-center h-100">
                        <div class="card-body bg-success">
                                <i class="fa fa-user fa-4x"></i>
                            <h4 class="text-uppercase">Users</h4>
                            <h1 class="display-4">{{customers.all.count}}</h1>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-sm-6 py-2">
                    <div class="card text-white bg-danger text-center h-100">
                        <div class="card-body bg-danger">
                                <i class="fa fa-list fa-4x"></i>
                            <h4 class="text-uppercase">Products</h4>
                            <h1 class="display-4">{{products.all.count}}</h1>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-sm-6 py-2">
                    <div class="card text-white bg-info h-100">
                        <div class="card-body bg-info">
                            <div class="rotate">
                                <i class="fa fa-twitter fa-4x"></i>
                            </div>
                            <h6 class="text-uppercase">Brands</h6>
                            <h1 class="display-4">{{brands.all.count}}</h1>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-sm-6 py-2">
                    <div class="card text-white bg-warning h-100">
                        <div class="card-body">
                            <div class="rotate">
                                <i class="fa fa-share fa-4x"></i>
                            </div>
                            <h6 class="text-uppercase">Categorys</h6>
                            <h1 class="display-4">{{categorys.all.count}}</h1>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-sm-6 py-2">
                    <div class="card text-white bg-info h-100">
                        <div class="card-body bg-info">
                            <div class="rotate">
                                <i class="fa fa-twitter fa-4x"></i>
                            </div>
                            <h6 class="text-uppercase">Orders</h6>
                            <h1 class="display-4">{{orders.all.count}}</h1>
                        </div>
                    </div>
                </div>
                <div class="col-xl-3 col-sm-6 py-2">
                    <div class="card text-white bg-info h-100">
                        <div class="card-body bg-info">
                            <div class="rotate">
                                <i class="fa fa-twitter fa-4x"></i>
                            </div>
                            <h6 class="text-uppercase">Pending Orders</h6>
                            <h1 class="display-4">{{pendingorders.all.count}}</h1>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

main/templates/adminhome.html
{% extends 'adminbase3.html' %}
{% load static %}
{% load humanize %}
{% block title %} ShopIT Admin-Panel {% endblock %}
{% block content %}
    <div class="row">
        <div class="col-md-5">
            <br />
            <h3>No. of Users</h3>
            <hr>
            <table class="table table-hover">
                <thead class="thead-dark">
                    <tr>
                        <th>SN</th>
                        <th>username</th>
                        <th>Joined On</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cust in customers %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{cust.user.username}}</td>
                        <td>{{cust.joined_on}}</td>
                        <td><a href="{% url 'deletecustomer' cust.user.id %}"
                                onclick="return confirm('Are you sure you want to delete this user?')"
                                class="btn btn-danger"> DELETE </a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-md-7">
            <br />
            <div style="float: left;">
                <h3>Pending Orders</h3>
            </div>
            <div style="float: right;"><a href="{% url 'adminOrderList' %}" class="btn btn-success">All Orders</a></div>
            <br />
            <hr class="mt-4">
            <table class="table table-hover">
                <thead class="thead-dark">
                    <tr>
                        <th>SN</th>
                        <th>Order ID </th>
                        <th>Customer</th>
                        <th>Ordered On</th>
                        <th>Amount</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order in pendingorders %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td><a href="{% url 'adminOrderDetails' order.id %}">#ORDER_{{order.id}}</a></td>
                        <td>{{order.ordered_by}}</td>
                        <td>{{order.created_at}}</td>
                        <td>Rs. {{order.total|intcomma}}</td>

                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        <div class="col-md-12">
            <br />
            <h3>Product List</h3>
            <hr>
            <table class="table table-hover">
                <thead class="thead-dark">
                    <tr>
                        <th>SN</th>
                        <th>Name</th>
                        <th>Category</th>
                        <th>Brand</th>
                        <th>Color</th>
                        <th>Price</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for product in products %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td><a href="{% url 'product-detail' slug=product.slug id=product.id %}"
                                target="_blank">{{product.title}}</a></td>
                        <td>{{product.category}}</td>
                        <td>{{product.brand}}</td>
                        <td>{{product.productattribute_set.first.color}}</td>
                        <td>Rs. {{product.price|intcomma}}</td>
                        <td><a href="{% url 'deleteproduct' product.id %}"
                                onclick="return confirm('Are you sure you want to delete this product?')"
                                class="btn btn-danger"> DELETE </a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

{% endblock %}

main/templates/category_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">
    <!-- Featured Products -->
    <h3 class="my-4 border-bottom pb-1">Categories</h3>
    <div class="row">
        {% if data %}
        {% for cat in data %}
        <div class="col-md-3 mb-4">
            <div class="card shadow">
                <a href="/category-product-list/{{cat.id}}"><img src="/media/{{cat.image}}" class="card-img-top"
                        alt="{{cat.title}}" /></a>
                <div class="card-body">
                    <h6 class="card-text"><a href="#">{{cat.title}}</a></h6>
                </div>
            </div>
        </div>
        {% endfor %}
        {% endif %}
    </div>
</main>
{% endblock %}

main/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!-- Home Slider -->
<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        {% for banner in banners %}
        {% if forloop.counter == 1 %}
            <li data-target="#carouselExampleIndicators" data-slide-to="{{forloop.counter}}" class="active"></li>
        {% else %}
        <li data-target="#carouselExampleIndicators" data-slide-to="{{forloop.counter}}"></li>
        {% endif %}
        {% endfor %}

    </ol>
    <div class="carousel-inner">
        {% for banner in banners %}
        {% if forloop.counter == 1 %}
        <div class="carousel-item active">
            {% else %}
            <div class="carousel-item">
            {% endif %}
            <img src="/media/{{banner.img}}" class="d-block w-100" alt="{{banner.title}}">
        </div>
        {% endfor %}
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>
<main class="container my-4">
    <!-- Featured Products -->
            <div style="float: left;">
                <h3>Featured Products</h3>
            </div>
            <div style="float: right;"><a href="{% url 'product-list' %}" class="btn btn-primary">All Products&nbsp;<i class="fas fa-arrow-right"></i></a></div>
            <br />
        <hr class="mt-4">
    <div class="row">
        {% for product in data %}
        <div class="col-md-3 mb-4">
            <div class="card shadow">
                <a href="/product/{{product.slug}}/{{product.id}}"><img src="/media/{{product.productattribute_set.first.image}}" class="card-img-top" alt="{{product.title}}"></a>
                <div class="card-body">
                    <h5 class="card-text"><a href="/product/{{product.slug}}/{{product.id}}">{{product.title}}</a></h5>
                    <h6>Rs. {{product.price}}</h6>
                </div>
                <div class="card-footer">
                    <a href = "{% url 'addtocart' product.id %}"><button class="btn btn-sm btn-primary" ><i class="fa fa-shopping-cart"></i></button></a>
                    <a href = "{% url 'addToFavourite' product.id %}"><button class="btn btn-sm btn-danger"><i class="fa fa-heart"></i></button></a>
                    <span class="float-right">
                        4.5/5
                        <i class="fa fa-star text-warning"></i>
                    </span>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</main>
{% endblock %}

main/templates/product_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<main class="container my-4">
	<div class="row">
		<!-- Filters -->
		<div class="col-md-3">
			{% include 'filters.html' %}
		</div>
		<div class="col-md-9">
			<!-- Products -->
			<h3 class="mb-4 border-bottom pb-1">
				Products
			</h3>
			<div class="row" id="filteredProducts">
				<p class="ajaxLoader">Loading...</p>
				{% for product in data %}
				<div class="col-lg-4 col-md-6 mb-4">
					<div class="card shadow">
					  <a href="/product/{{product.slug}}/{{product.id}}"><img src="/media/{{product.productattribute_set.first.image}}" class="card-img-top" alt="{{product.title}}"></a>
					  <div class="card-body">
					    <h5 class="card-text"><a href="/product/{{product.slug}}/{{product.id}}">{{product.title}}</a></h5>
					    <h6>Rs. {{product.price}}</h6>
					  </div>
					  <div class="card-footer">
					  	<a href="{% url 'addtocart' product.id %}"><button class="btn btn-sm btn-primary"><i class="fa fa-shopping-cart"></i></button></a>
					  	<a href = "{% url 'addToFavourite' product.id %}"><button class="btn btn-sm btn-danger"><i class="fa fa-heart"></i></button></a>
					  	<span class="float-right">
					  		4.5/5
					  		<i class="fa fa-star text-warning"></i>
					  	</span>
					  </div>
					</div>
				</div>
				{% endfor %}
			</div>
		</div>
	</div>
</main>
{% endblock %}

main/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<main class="container my-4">
    <!-- Featured Products -->
    <h3 class="my-4 border-bottom pb-1"><span class="text-muted">Search Results for {{request.GET.q}}</span></h3>
    <div class="row">
        {% for product in data %}
        <div class="col-md-3 mb-4">
            <div class="card shadow">
                <a href="/product/{{product.slug}}/{{product.id}}"><img src="/media/{{product.productattribute_set.first.image}}" class="card-img-top" alt="{{product.title}}"></a>
                <div class="card-body">
                    <h5 class="card-text"><a href="/product/{{product.slug}}/{{product.id}}">{{product.title}}</a></h5>
                    <h6>Rs. {{product.price}}</h6>
                </div>
                <div class="card-footer">
                    <button class="btn btn-sm btn-primary"><i class="fa fa-shopping-cart"></i></button>
                    <button class="btn btn-sm btn-danger"><i class="fa fa-heart"></i></button>
                    <span class="float-right">
                        4.5/5
                        <i class="fa fa-star text-warning"></i>
                    </span>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</main>
{% endblock %}